using System.Text.Json.Serialization;

namespace Reka.SDK.Vision;

/// <summary>
/// Represents the answer from a QA (Question Answering) model.
/// </summary>
public class QAAnswer
{
    /// <summary>
    /// The chat response generated by the QA model.
    /// </summary>
    [JsonPropertyName("chat_response")]
    public string ChatResponse { get; set; } = string.Empty;

    /// <summary>
    /// An optional system message providing additional context or information.
    /// </summary>
    [JsonPropertyName("system_message")]
    public string? SystemMessage { get; set; }

    /// <summary>
    /// An optional error message if an error occurred during processing.
    /// </summary>
    [JsonPropertyName("error")]
    public string? Error { get; set; }

    /// <summary>
    /// The status of the QA response.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;

    /// <summary>
    /// Debug information about the chunks used in generating the answer.
    /// </summary>
    [JsonPropertyName("debug_chunks")]
    public object? DebugChunks { get; set; }

    /// <summary>
    /// Debug information about the predicted start time.
    /// </summary>
    [JsonPropertyName("debug_predicted_start_time")]
    public string DebugPredictedStartTime { get; set; } = string.Empty;

    /// <summary>
    /// Debug information about the predicted end time.
    /// </summary>
    [JsonPropertyName("debug_predicted_end_time")]
    public string DebugPredictedEndTime { get; set; } = string.Empty;
}