<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Reka.SDK</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet Package Metadata -->
    <PackageId>Reka.SDK</PackageId>
    <Version>0.1.3-beta</Version>
    <Authors>Frank Boucher (fboucher), Reka</Authors>
    <Company>Reka</Company>
    <Description>Official .NET SDK for Reka AI API - A SDK for integrating Reka's AI APIs into your .NET applications.</Description>
    <PackageTags>reka;ai;sdk;dotnet;api;vision;research;chat</PackageTags>
    <RepositoryUrl>https://github.com/reka-ai/reka-sdk-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://reka.ai</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
    <None Include="icon.png" Pack="true" PackagePath=""/>
  </ItemGroup>

</Project>
